### Updates and existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe Updated1",
  "email": "john.doe.update@jd.com",
  "address": "123 main street",
  "dateOfBirth": "1991-01-01"
}


###